// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Match struct {
	UID         string     `json:"uid"`
	Name        string     `json:"name"`
	Score1      *string    `json:"score1"`
	Score2      *string    `json:"score2"`
	Player1     *Player    `json:"player1"`
	Player2     *Player    `json:"player2"`
	ScheduledOn time.Time  `json:"scheduledOn"`
	StartedOn   *time.Time `json:"startedOn"`
	CompletedOn *time.Time `json:"completedOn"`
}

type Player struct {
	UID  string `json:"uid"`
	Name string `json:"name"`
}

type TournamentInfo struct {
	UID     string    `json:"uid"`
	Name    string    `json:"name"`
	Players []*Player `json:"players"`
	Matches []*Match  `json:"matches"`
}
